// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrv7f-oniQ8LQyJbHtTSCEAKCFz6bI7Hg',
    appId: '1:66574415093:web:f2eb006c998942a36101bc',
    messagingSenderId: '66574415093',
    projectId: 'esof-b6ccb',
    authDomain: 'esof-b6ccb.firebaseapp.com',
    storageBucket: 'esof-b6ccb.appspot.com',
    measurementId: 'G-X4K4S0ZB29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAmXc_0v9mUvUaxNJuzifZo8qQUxQx3Zc',
    appId: '1:66574415093:android:b699686b21d934b26101bc',
    messagingSenderId: '66574415093',
    projectId: 'esof-b6ccb',
    storageBucket: 'esof-b6ccb.appspot.com',
  );
}
